# Generated by Django 3.0.7 on 2020-07-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200707_1826'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='Order_Detail',
        ),
    ]
