import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "onlineShop.settings")
django.setup()


from shopping.models import Category
from django.utils import timezone
from datetime import datetime

sportware = Category.objects.get(pk=1)#Category(name='SPORTSWEAR', description='SPORTSWEAR')
#sportware.save()

NIKE = Category(name='NIKE', description='NIKE', cate_parent_id=sportware.id)
NIKE.save()
UNDER_ARMOUR = Category(name='UNDER ARMOUR', description='UNDER ARMOUR', cate_parent_id=sportware.id)
UNDER_ARMOUR.save()
ADIDAS = Category(name='ADIDAS', description='ADIDAS', cate_parent_id=sportware.id)
ADIDAS.save()
PUMA = Category(name='PUMA', description='PUMA', cate_parent_id=sportware.id)
PUMA.save()
ASICS = Category(name='ASICS', description='ASICS', cate_parent_id=sportware.id)
ASICS.save()

MENS =Category(name='MENS', description='MENS')
MENS.save()
FENDI = Category(name='FENDI', description='FENDI', cate_parent_id=MENS.id)
FENDI.save()
GUESS = Category(name='GUESS', description='GUESS', cate_parent_id=MENS.id)
GUESS.save()
VALENTINO = Category(name='VALENTINO', description='VALENTINO', cate_parent_id=MENS.id)
VALENTINO.save()
DIOR = Category(name='DIOR', description='DIOR', cate_parent_id=MENS.id)
DIOR.save()
VERSACE = Category(name='VERSACE', description='VERSACE', cate_parent_id=MENS.id)
VERSACE.save()
ARMANI = Category(name='ARMANI', description='ARMANI', cate_parent_id=MENS.id)
ARMANI.save()
PRADA = Category(name='PRADA', description='PRADA', cate_parent_id=MENS.id)
PRADA.save()
DOLCE_AND_GABBANA = Category(name='DOLCE AND GABBANA', description='DOLCE AND GABBANA', cate_parent_id=MENS.id)
DOLCE_AND_GABBANA.save()
CHANEL = Category(name='CHANEL', description='CHANEL', cate_parent_id=MENS.id)
CHANEL.save()
GUCCI = Category(name='GUCCI', description='GUCCI', cate_parent_id=MENS.id)
GUCCI.save()

WOMENS =Category(name='WOMENS', description='WOMENS')
WOMENS.save()
FENDI_WOMENS = Category(name='FENDI', description='FENDI', cate_parent_id=WOMENS.id)
FENDI_WOMENS.save()
GUESS_WOMENS = Category(name='GUESS', description='GUESS', cate_parent_id=WOMENS.id)
GUESS_WOMENS.save()
VALENTINO_WOMENS = Category(name='VALENTINO', description='VALENTINO', cate_parent_id=WOMENS.id)
VALENTINO_WOMENS.save()
DIOR_WOMENS = Category(name='DIOR', description='DIOR', cate_parent_id=WOMENS.id)
DIOR_WOMENS.save()
VERSACE_WOMENS = Category(name='VERSACE', description='VERSACE', cate_parent_id=WOMENS.id)
VERSACE_WOMENS.save()

KIDS =Category(name='KIDS', description='KIDS')
KIDS.save()
FASHION =Category(name='FASHION', description='FASHION')
FASHION.save()
HOUSEHOLDS =Category(name='HOUSEHOLDS', description='HOUSEHOLDS')
HOUSEHOLDS.save()
INTERIORS =Category(name='INTERIORS', description='INTERIORS')
INTERIORS.save()
CLOTHING =Category(name='CLOTHING', description='CLOTHING')
CLOTHING.save()
BAGS =Category(name='BAGS', description='BAGS')
BAGS.save()
SHOES =Category(name='SHOES', description='SHOES')
SHOES.save()
